
abx = structure(c(1L, 2L, 4L, 5L, 6L, 8L, 11L, 12L, 13L, 15L, 19L, 
            21L, 23L, 24L, 25L, 26L, 27L, 34L, 35L, 36L, 37L, 39L, 40L, 41L, 
            42L, 44L, 48L, 49L, 46L, 38L, 43L, 52L, 30L, 47L, 9L, 
            45L, 10L, 29L, 14L, 51L, 28L, 31L, 50L, 17L, 18L, 33L, 22L, 32L, 
            7L, 16L, 3L, 20L), .Label = c("Amik.Fluclox", "Amikacin", 
                                          "Ampicillin", "Augmentin", "Cefotaxime", "Cefoxitin", "Ceftazidime", 
                                          "Ceftriaxone", "Cefuroxime", "Cephradine", "Chloramphenicol", 
                                          "Ciprofloxacin", "Clindamycin", "Colistin", "Co.Trimoxazole..Septrin.", 
                                          "Daptomycin", "Doxycycline", "Erythromycin", "Flucloxacillin", 
                                          "Fosfomycin", "Fucidin", "Gent.Ceftaz", "Gent.Cipro", "Gent.Pip.Taz", 
                                          "Gentamicin", "Imipenem", "Linezolid", "Mecillinam", "Meropenem", 
                                          "Metronidazole", "Minocycline", "Mupirocin", "Naladixic.Acid", 
                                          "Neomycin", "Nitrofurantoin", "Oxacillin", "Penicillin", "Piperacillin...Tazobactam", 
                                          "Pip.Taz.Amik", "Pip.Taz.Cipro", "Pristinomycin", "Rifampicin", 
                                          "Septrin", "Sulphonamide", "Syncercid", "Teicoplanin", "Tetracycline", 
                                          "Tigecycline", "Timentin", "Tobramycin", "Trimethoprim", "Vancomycin"
            ), class = "factor")


abx_classes = data.frame(abx = as.character(abx), class = NA)
abx_classes$class = c("Mixed",
                      "Aminoglycosides",
                      "Penicillins",
                      "Penicillins",
                      "Cephalosporins",
                      "Cephalosporins",
                      "Cephalosporins",
                      "Others",
                      "Fluoroquinolones",
                      "Polypetides",
                      "Macrolides",
                      "Penicillins",
                      "Others",
                      "Mixed",
                      "Mixed",
                      "Mixed",
                      "Aminoglycosides",
                      "Other",
                      "Fluoroquinolones",
                      "Aminoglycosides",
                      "Nitrofurans",
                      "Penicillins",
                      "Mixed",
                      "Mixed",
                      "Mixed",
                      "Antimycobacterials",
                      "Glycopeptides",
                      "Tetracyclines",
                      "Others",
                      "Glycopeptides",
                      "Sulphonamides",
                      "Penicillins",
                      "Others",
                      "Aminoglycosides",
                      "Penicillins",
                      "Others",
                      "Cephalosporins",
                      "Sulfonamides",
                      "Cephalosporins",
                      "Oxazolidinones",
                      "Lincosamides",
                      "Mixed",
                      "Carbapenems",
                      "Carbapenems",
                      "Others",
                      "Lipopetides",
                      "Tetracyclines",
                      "Tetracyclines",
                      "Others",
                      "Others",
                      "Cephalosporins",
                      "Sulfonamides")

dput(abx_classes)
